### ISSUE TITLE
"Toggle visibility" button is bugged in french translation

### ISSUE THREAD

**Issue by MaximGi** [JonnyNova/Rimworld-Shields#21]
See attached image
![image](https://user-images.githubusercontent.com/34157556/33677980-d12e21a6-daba-11e7-9e4b-9e7c7e89cd5d.png)

Seems like an encoding issue

- Happens on the three different shields
How to reproduce :
Play the game with french language

**Comment by JonnyNova** [comment]
That happens when a key doesn't exist for a language. Could you add the right French translation for the key ```<fd.shield.render_field.label>```? It should go here: https://github.com/JonnyNova/Rimworld-Shields/blob/master/Languages/French/Keyed/UI.xml

**Comment by MaximGi** [comment]
Done
