### ISSUE TITLE
Add missing French translations

### ISSUE THREAD

**Issue by JonnyNova** [JonnyNova/Rimworld-Shields#55]
Settings to enable/disable mod integrations:
https://github.com/JonnyNova/Rimworld-Shields/blob/a911c61a57516ad737c50305feffd1e3357d5286/Languages/English/Keyed/English.xml#L6-L13

Shield settings:
https://github.com/JonnyNova/Rimworld-Shields/blob/a911c61a57516ad737c50305feffd1e3357d5286/Languages/English/Keyed/English.xml#L15-L25

UI gizmo to connect/disconnect a shield from a Centralized Climate Control air network:
https://github.com/JonnyNova/Rimworld-Shields/blob/a911c61a57516ad737c50305feffd1e3357d5286/Languages/English/Keyed/English.xml#L101-L102

**Comment by Paladorn** [comment]
#61
