### ISSUE TITLE
W40k Astra Militarum Projectiles Unsupported

### ISSUE THREAD

**Issue by jetpack-maniac** [JonnyNova/Rimworld-Shields#62]
This mod uses a different base class for its projectiles.  It uses "IG_BaseBullet" found in Weapons_QXIGC-BaseAstracts.xml under ThingDefs.

Forum post: https://ludeon.com/forums/index.php?topic=26469.0

**Comment by JonnyNova** [comment]
The grenade launcher shoots mortars. Fixed with fe394703297f9d7ce04ccf345a313633482ba1aa
