### ISSUE TITLE
CombatExtended 1.0 support

### ISSUE THREAD

**Issue by JonnyNova** [JonnyNova/Rimworld-Shields#64]
**Projectiles**
- [ ] Block bullets
- [ ] Detonate explosives on impact
- [ ] Simulate mortar explosion by blocking fragments
- [ ] Apply secondary damage types to shields

**Explosions**
- [ ] Add shield check to `ExplosionCE.AffectCell`

**Verbs**
- [ ] Add shield check to `Verb_LaunchProjectileCE.CanHitTargetFrom`

**Comment by Valerate** [comment]
Hi, is there anything I could do to help this?

**Comment by JonnyNova** [comment]
@Valerate absolutely! I'm fully booked with work related things until mid December and will absolutely have no time to work on it. If you submit a PR to handle this I would be more than happy to get it merged

**Comment by JonnyNova** [comment]
What I had started working on is up on `wip-combat-extended` branch

**Comment by JonnyNova** [comment]
Added initial support. Moving enhancements to another issue
