### ISSUE TITLE
Large Shield Generator does not work with Climate Control

### ISSUE THREAD

**Issue by aspenforest** [JonnyNova/Rimworld-Shields#74]
I built a large shield generator and piped a large climate control unit set to -273 degrees into it, the room temperature was 13 degrees. When the shield was connected with the climate control, its temperature rose to 21 degrees, when disconnected from the climate control, it dropped to the room temperature. It does not make any sense.
I have two small shield generators connected with the same climate control unit and they properly drop down to -273 degrees, while at the same time the large shield increases to 21 degrees, which is above the ambient room temperature, when connected with the same climate control unit.
I'm using the latest versions of both mods and shields is loaded after climate control.

**Comment by JonnyNova** [comment]
I could not reproduce. Is this still an issue for you?

**Comment by aspenforest** [comment]
Don't remember what it was exactly about, I don't play anymore.
